var cerealI = [
 {
   "name": "100%_Bran",
   "manufacturer": "Nabisco",
   "Type": "C",
   "calories": 70,
   "Protein (g)": 4,
   "Fat": 1,
   "Sodium": 130,
   "Dietary Fiber": 10,
   "Carbs": 5,
   "sugar": 6,
   "Display Shelf": 3,
   "potassium": 280,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.33
 },
 {
   "name": "100%_Natural_Bran",
   "manufacturer": "Quaker Oats",
   "Type": "C",
   "calories": 120,
   "Protein (g)": 3,
   "Fat": 5,
   "Sodium": 15,
   "Dietary Fiber": 2,
   "Carbs": 8,
   "sugar": 8,
   "Display Shelf": 3,
   "potassium": 135,
   "vitamins": 0,
   "Serving Size Weight": 1,
   "Cups per Serving": -1
 },
 {
   "name": "All-Bran",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 70,
   "Protein (g)": 4,
   "Fat": 1,
   "Sodium": 260,
   "Dietary Fiber": 9,
   "Carbs": 7,
   "sugar": 5,
   "Display Shelf": 3,
   "potassium": 320,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.33
 },
 {
   "name": "All-Bran_with_Extra_Fiber",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 50,
   "Protein (g)": 4,
   "Fat": 0,
   "Sodium": 140,
   "Dietary Fiber": 14,
   "Carbs": 8,
   "sugar": 0,
   "Display Shelf": 3,
   "potassium": 330,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.5
 },
 {
   "name": "Almond_Delight",
   "manufacturer": "Ralston Purina",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 2,
   "Fat": 2,
   "Sodium": 200,
   "Dietary Fiber": 1,
   "Carbs": 14,
   "sugar": 8,
   "Display Shelf": 3,
   "potassium": -1,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.75
 },
 {
   "name": "Apple_Cinnamon_Cheerios",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 2,
   "Fat": 2,
   "Sodium": 180,
   "Dietary Fiber": 1.5,
   "Carbs": 10.5,
   "sugar": 10,
   "Display Shelf": 1,
   "potassium": 70,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.75
 },
 {
   "name": "Apple_Jacks",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 2,
   "Fat": 0,
   "Sodium": 125,
   "Dietary Fiber": 1,
   "Carbs": 11,
   "sugar": 14,
   "Display Shelf": 2,
   "potassium": 30,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 1
 },
 {
   "name": "Basic_4",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 130,
   "Protein (g)": 3,
   "Fat": 2,
   "Sodium": 210,
   "Dietary Fiber": 2,
   "Carbs": 18,
   "sugar": 8,
   "Display Shelf": 3,
   "potassium": 100,
   "vitamins": 25,
   "Serving Size Weight": 1.33,
   "Cups per Serving": 0.75
 },
 {
   "name": "Bran_Chex",
   "manufacturer": "Ralston Purina",
   "Type": "C",
   "calories": 90,
   "Protein (g)": 2,
   "Fat": 1,
   "Sodium": 200,
   "Dietary Fiber": 4,
   "Carbs": 15,
   "sugar": 6,
   "Display Shelf": 1,
   "potassium": 125,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.67
 },
 {
   "name": "Bran_Flakes",
   "manufacturer": "Post",
   "Type": "C",
   "calories": 90,
   "Protein (g)": 3,
   "Fat": 0,
   "Sodium": 210,
   "Dietary Fiber": 5,
   "Carbs": 13,
   "sugar": 5,
   "Display Shelf": 3,
   "potassium": 190,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.67
 },
 {
   "name": "Cap'n'Crunch",
   "manufacturer": "Quaker Oats",
   "Type": "C",
   "calories": 120,
   "Protein (g)": 1,
   "Fat": 2,
   "Sodium": 220,
   "Dietary Fiber": 0,
   "Carbs": 12,
   "sugar": 12,
   "Display Shelf": 2,
   "potassium": 35,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.75
 },
 {
   "name": "Cheerios",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 6,
   "Fat": 2,
   "Sodium": 290,
   "Dietary Fiber": 2,
   "Carbs": 17,
   "sugar": 1,
   "Display Shelf": 1,
   "potassium": 105,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 1.25
 },
 {
   "name": "Cinnamon_Toast_Crunch",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 120,
   "Protein (g)": 1,
   "Fat": 3,
   "Sodium": 210,
   "Dietary Fiber": 0,
   "Carbs": 13,
   "sugar": 9,
   "Display Shelf": 2,
   "potassium": 45,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.75
 },
 {
   "name": "Clusters",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 3,
   "Fat": 2,
   "Sodium": 140,
   "Dietary Fiber": 2,
   "Carbs": 13,
   "sugar": 7,
   "Display Shelf": 3,
   "potassium": 105,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.5
 },
 {
   "name": "Cocoa_Puffs",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 1,
   "Fat": 1,
   "Sodium": 180,
   "Dietary Fiber": 0,
   "Carbs": 12,
   "sugar": 13,
   "Display Shelf": 2,
   "potassium": 55,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 1
 },
 {
   "name": "Corn_Chex",
   "manufacturer": "Ralston Purina",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 2,
   "Fat": 0,
   "Sodium": 280,
   "Dietary Fiber": 0,
   "Carbs": 22,
   "sugar": 3,
   "Display Shelf": 1,
   "potassium": 25,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 1
 },
 {
   "name": "Corn_Flakes",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 100,
   "Protein (g)": 2,
   "Fat": 0,
   "Sodium": 290,
   "Dietary Fiber": 1,
   "Carbs": 21,
   "sugar": 2,
   "Display Shelf": 1,
   "potassium": 35,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 1
 },
 {
   "name": "Corn_Pops",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 1,
   "Fat": 0,
   "Sodium": 90,
   "Dietary Fiber": 1,
   "Carbs": 13,
   "sugar": 12,
   "Display Shelf": 2,
   "potassium": 20,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 1
 },
 {
   "name": "Count_Chocula",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 1,
   "Fat": 1,
   "Sodium": 180,
   "Dietary Fiber": 0,
   "Carbs": 12,
   "sugar": 13,
   "Display Shelf": 2,
   "potassium": 65,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 1
 },
 {
   "name": "Cracklin'_Oat_Bran",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 3,
   "Fat": 3,
   "Sodium": 140,
   "Dietary Fiber": 4,
   "Carbs": 10,
   "sugar": 7,
   "Display Shelf": 3,
   "potassium": 160,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.5
 },
 {
   "name": "Cream_of_Wheat_(Quick)",
   "manufacturer": "Nabisco",
   "Type": "H",
   "calories": 100,
   "Protein (g)": 3,
   "Fat": 0,
   "Sodium": 80,
   "Dietary Fiber": 1,
   "Carbs": 21,
   "sugar": 0,
   "Display Shelf": 2,
   "potassium": -1,
   "vitamins": 0,
   "Serving Size Weight": 1,
   "Cups per Serving": 1
 },
 {
   "name": "Crispix",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 2,
   "Fat": 0,
   "Sodium": 220,
   "Dietary Fiber": 1,
   "Carbs": 21,
   "sugar": 3,
   "Display Shelf": 3,
   "potassium": 30,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 1
 },
 {
   "name": "Crispy_Wheat_&_Raisins",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 100,
   "Protein (g)": 2,
   "Fat": 1,
   "Sodium": 140,
   "Dietary Fiber": 2,
   "Carbs": 11,
   "sugar": 10,
   "Display Shelf": 3,
   "potassium": 120,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.75
 },
 {
   "name": "Double_Chex",
   "manufacturer": "Ralston Purina",
   "Type": "C",
   "calories": 100,
   "Protein (g)": 2,
   "Fat": 0,
   "Sodium": 190,
   "Dietary Fiber": 1,
   "Carbs": 18,
   "sugar": 5,
   "Display Shelf": 3,
   "potassium": 80,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.75
 },
 {
   "name": "Froot_Loops",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 2,
   "Fat": 1,
   "Sodium": 125,
   "Dietary Fiber": 1,
   "Carbs": 11,
   "sugar": 13,
   "Display Shelf": 2,
   "potassium": 30,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 1
 },
 {
   "name": "Frosted_Flakes",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 1,
   "Fat": 0,
   "Sodium": 200,
   "Dietary Fiber": 1,
   "Carbs": 14,
   "sugar": 11,
   "Display Shelf": 1,
   "potassium": 25,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.75
 },
 {
   "name": "Frosted_Mini-Wheats",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 100,
   "Protein (g)": 3,
   "Fat": 0,
   "Sodium": 0,
   "Dietary Fiber": 3,
   "Carbs": 14,
   "sugar": 7,
   "Display Shelf": 2,
   "potassium": 100,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.8
 },
 {
   "name": "Fruitful_Bran",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 120,
   "Protein (g)": 3,
   "Fat": 0,
   "Sodium": 240,
   "Dietary Fiber": 5,
   "Carbs": 14,
   "sugar": 12,
   "Display Shelf": 3,
   "potassium": 190,
   "vitamins": 25,
   "Serving Size Weight": 1.33,
   "Cups per Serving": 0.67
 },
 {
   "name": "Fruity_Pebbles",
   "manufacturer": "Post",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 1,
   "Fat": 1,
   "Sodium": 135,
   "Dietary Fiber": 0,
   "Carbs": 13,
   "sugar": 12,
   "Display Shelf": 2,
   "potassium": 25,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.75
 },
 {
   "name": "Golden_Crisp",
   "manufacturer": "Post",
   "Type": "C",
   "calories": 100,
   "Protein (g)": 2,
   "Fat": 0,
   "Sodium": 45,
   "Dietary Fiber": 0,
   "Carbs": 11,
   "sugar": 15,
   "Display Shelf": 1,
   "potassium": 40,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.88
 },
 {
   "name": "Golden_Grahams",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 1,
   "Fat": 1,
   "Sodium": 280,
   "Dietary Fiber": 0,
   "Carbs": 15,
   "sugar": 9,
   "Display Shelf": 2,
   "potassium": 45,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.75
 },
 {
   "name": "Grape_Nuts_Flakes",
   "manufacturer": "Post",
   "Type": "C",
   "calories": 100,
   "Protein (g)": 3,
   "Fat": 1,
   "Sodium": 140,
   "Dietary Fiber": 3,
   "Carbs": 15,
   "sugar": 5,
   "Display Shelf": 3,
   "potassium": 85,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.88
 },
 {
   "name": "Grape-Nuts",
   "manufacturer": "Post",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 3,
   "Fat": 0,
   "Sodium": 170,
   "Dietary Fiber": 3,
   "Carbs": 17,
   "sugar": 3,
   "Display Shelf": 3,
   "potassium": 90,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.25
 },
 {
   "name": "Great_Grains_Pecan",
   "manufacturer": "Post",
   "Type": "C",
   "calories": 120,
   "Protein (g)": 3,
   "Fat": 3,
   "Sodium": 75,
   "Dietary Fiber": 3,
   "Carbs": 13,
   "sugar": 4,
   "Display Shelf": 3,
   "potassium": 100,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.33
 },
 {
   "name": "Honey_Graham_Ohs",
   "manufacturer": "Quaker Oats",
   "Type": "C",
   "calories": 120,
   "Protein (g)": 1,
   "Fat": 2,
   "Sodium": 220,
   "Dietary Fiber": 1,
   "Carbs": 12,
   "sugar": 11,
   "Display Shelf": 2,
   "potassium": 45,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 1
 },
 {
   "name": "Honey_Nut_Cheerios",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 3,
   "Fat": 1,
   "Sodium": 250,
   "Dietary Fiber": 1.5,
   "Carbs": 11.5,
   "sugar": 10,
   "Display Shelf": 1,
   "potassium": 90,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.75
 },
 {
   "name": "Honey-comb",
   "manufacturer": "Post",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 1,
   "Fat": 0,
   "Sodium": 180,
   "Dietary Fiber": 0,
   "Carbs": 14,
   "sugar": 11,
   "Display Shelf": 1,
   "potassium": 35,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 1.33
 },
 {
   "name": "Just_Right_Crunchy__Nuggets",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 2,
   "Fat": 1,
   "Sodium": 170,
   "Dietary Fiber": 1,
   "Carbs": 17,
   "sugar": 6,
   "Display Shelf": 3,
   "potassium": 60,
   "vitamins": 100,
   "Serving Size Weight": 1,
   "Cups per Serving": -1
 },
 {
   "name": "Just_Right_Fruit_&_Nut",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 140,
   "Protein (g)": 3,
   "Fat": 1,
   "Sodium": 170,
   "Dietary Fiber": 2,
   "Carbs": 20,
   "sugar": 9,
   "Display Shelf": 3,
   "potassium": 95,
   "vitamins": 100,
   "Serving Size Weight": 1.3,
   "Cups per Serving": 0.75
 },
 {
   "name": "Kix",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 2,
   "Fat": 1,
   "Sodium": 260,
   "Dietary Fiber": 0,
   "Carbs": 21,
   "sugar": 3,
   "Display Shelf": 2,
   "potassium": 40,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 1.5
 },
 {
   "name": "Life",
   "manufacturer": "Quaker Oats",
   "Type": "C",
   "calories": 100,
   "Protein (g)": 4,
   "Fat": 2,
   "Sodium": 150,
   "Dietary Fiber": 2,
   "Carbs": 12,
   "sugar": 6,
   "Display Shelf": 2,
   "potassium": 95,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.67
 },
 {
   "name": "Lucky_Charms",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 2,
   "Fat": 1,
   "Sodium": 180,
   "Dietary Fiber": 0,
   "Carbs": 12,
   "sugar": 12,
   "Display Shelf": 2,
   "potassium": 55,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 1
 },
 {
   "name": "Maypo",
   "manufacturer": "American Home Food Products",
   "Type": "H",
   "calories": 100,
   "Protein (g)": 4,
   "Fat": 1,
   "Sodium": 0,
   "Dietary Fiber": 0,
   "Carbs": 16,
   "sugar": 3,
   "Display Shelf": 2,
   "potassium": 95,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": -1
 },
 {
   "name": "Mueslix_Crispy_Blend",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 160,
   "Protein (g)": 3,
   "Fat": 2,
   "Sodium": 150,
   "Dietary Fiber": 3,
   "Carbs": 17,
   "sugar": 13,
   "Display Shelf": 3,
   "potassium": 160,
   "vitamins": 25,
   "Serving Size Weight": 1.5,
   "Cups per Serving": 0.67
 },
 {
   "name": "Multi-Grain_Cheerios",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 100,
   "Protein (g)": 2,
   "Fat": 1,
   "Sodium": 220,
   "Dietary Fiber": 2,
   "Carbs": 15,
   "sugar": 6,
   "Display Shelf": 1,
   "potassium": 90,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 1
 },
 {
   "name": "Nut&Honey_Crunch",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 120,
   "Protein (g)": 2,
   "Fat": 1,
   "Sodium": 190,
   "Dietary Fiber": 0,
   "Carbs": 15,
   "sugar": 9,
   "Display Shelf": 2,
   "potassium": 40,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.67
 },
 {
   "name": "Nutri-Grain_Almond-Raisin",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 140,
   "Protein (g)": 3,
   "Fat": 2,
   "Sodium": 220,
   "Dietary Fiber": 3,
   "Carbs": 21,
   "sugar": 7,
   "Display Shelf": 3,
   "potassium": 130,
   "vitamins": 25,
   "Serving Size Weight": 1.33,
   "Cups per Serving": 0.67
 },
 {
   "name": "Nutri-grain_Wheat",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 90,
   "Protein (g)": 3,
   "Fat": 0,
   "Sodium": 170,
   "Dietary Fiber": 3,
   "Carbs": 18,
   "sugar": 2,
   "Display Shelf": 3,
   "potassium": 90,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": -1
 },
 {
   "name": "Oatmeal_Raisin_Crisp",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 130,
   "Protein (g)": 3,
   "Fat": 2,
   "Sodium": 170,
   "Dietary Fiber": 1.5,
   "Carbs": 13.5,
   "sugar": 10,
   "Display Shelf": 3,
   "potassium": 120,
   "vitamins": 25,
   "Serving Size Weight": 1.25,
   "Cups per Serving": 0.5
 },
 {
   "name": "Post_Nat._Raisin_Bran",
   "manufacturer": "Post",
   "Type": "C",
   "calories": 120,
   "Protein (g)": 3,
   "Fat": 1,
   "Sodium": 200,
   "Dietary Fiber": 6,
   "Carbs": 11,
   "sugar": 14,
   "Display Shelf": 3,
   "potassium": 260,
   "vitamins": 25,
   "Serving Size Weight": 1.33,
   "Cups per Serving": 0.67
 },
 {
   "name": "Product_19",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 100,
   "Protein (g)": 3,
   "Fat": 0,
   "Sodium": 320,
   "Dietary Fiber": 1,
   "Carbs": 20,
   "sugar": 3,
   "Display Shelf": 3,
   "potassium": 45,
   "vitamins": 100,
   "Serving Size Weight": 1,
   "Cups per Serving": 1
 },
 {
   "name": "Puffed_Rice",
   "manufacturer": "Quaker Oats",
   "Type": "C",
   "calories": 50,
   "Protein (g)": 1,
   "Fat": 0,
   "Sodium": 0,
   "Dietary Fiber": 0,
   "Carbs": 13,
   "sugar": 0,
   "Display Shelf": 3,
   "potassium": 15,
   "vitamins": 0,
   "Serving Size Weight": 0.5,
   "Cups per Serving": 1
 },
 {
   "name": "Puffed_Wheat",
   "manufacturer": "Quaker Oats",
   "Type": "C",
   "calories": 50,
   "Protein (g)": 2,
   "Fat": 0,
   "Sodium": 0,
   "Dietary Fiber": 1,
   "Carbs": 10,
   "sugar": 0,
   "Display Shelf": 3,
   "potassium": 50,
   "vitamins": 0,
   "Serving Size Weight": 0.5,
   "Cups per Serving": -1
 },
 {
   "name": "Quaker_Oat_Squares",
   "manufacturer": "Quaker Oats",
   "Type": "C",
   "calories": 100,
   "Protein (g)": 4,
   "Fat": 1,
   "Sodium": 135,
   "Dietary Fiber": 2,
   "Carbs": 14,
   "sugar": 6,
   "Display Shelf": 3,
   "potassium": 110,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.5
 },
 {
   "name": "Quaker_Oatmeal",
   "manufacturer": "Quaker Oats",
   "Type": "H",
   "calories": 100,
   "Protein (g)": 5,
   "Fat": 2,
   "Sodium": 0,
   "Dietary Fiber": 2.7,
   "Carbs": -1,
   "sugar": -1,
   "Display Shelf": 1,
   "potassium": 110,
   "vitamins": 0,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.67
 },
 {
   "name": "Raisin_Bran",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 120,
   "Protein (g)": 3,
   "Fat": 1,
   "Sodium": 210,
   "Dietary Fiber": 5,
   "Carbs": 14,
   "sugar": 12,
   "Display Shelf": 2,
   "potassium": 240,
   "vitamins": 25,
   "Serving Size Weight": 1.33,
   "Cups per Serving": 0.75
 },
 {
   "name": "Raisin_Nut_Bran",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 100,
   "Protein (g)": 3,
   "Fat": 2,
   "Sodium": 140,
   "Dietary Fiber": 2.5,
   "Carbs": 10.5,
   "sugar": 8,
   "Display Shelf": 3,
   "potassium": 140,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.5
 },
 {
   "name": "Raisin_Squares",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 90,
   "Protein (g)": 2,
   "Fat": 0,
   "Sodium": 0,
   "Dietary Fiber": 2,
   "Carbs": 15,
   "sugar": 6,
   "Display Shelf": 3,
   "potassium": 110,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.5
 },
 {
   "name": "Rice_Chex",
   "manufacturer": "Ralston Purina",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 1,
   "Fat": 0,
   "Sodium": 240,
   "Dietary Fiber": 0,
   "Carbs": 23,
   "sugar": 2,
   "Display Shelf": 1,
   "potassium": 30,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 1.13
 },
 {
   "name": "Rice_Krispies",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 2,
   "Fat": 0,
   "Sodium": 290,
   "Dietary Fiber": 0,
   "Carbs": 22,
   "sugar": 3,
   "Display Shelf": 1,
   "potassium": 35,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 1
 },
 {
   "name": "Shredded_Wheat",
   "manufacturer": "Nabisco",
   "Type": "C",
   "calories": 80,
   "Protein (g)": 2,
   "Fat": 0,
   "Sodium": 0,
   "Dietary Fiber": 3,
   "Carbs": 16,
   "sugar": 0,
   "Display Shelf": 1,
   "potassium": 95,
   "vitamins": 0,
   "Serving Size Weight": 0.83,
   "Cups per Serving": -1
 },
 {
   "name": "Shredded_Wheat_'n'Bran",
   "manufacturer": "Nabisco",
   "Type": "C",
   "calories": 90,
   "Protein (g)": 3,
   "Fat": 0,
   "Sodium": 0,
   "Dietary Fiber": 4,
   "Carbs": 19,
   "sugar": 0,
   "Display Shelf": 1,
   "potassium": 140,
   "vitamins": 0,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.67
 },
 {
   "name": "Shredded_Wheat_spoon_size",
   "manufacturer": "Nabisco",
   "Type": "C",
   "calories": 90,
   "Protein (g)": 3,
   "Fat": 0,
   "Sodium": 0,
   "Dietary Fiber": 3,
   "Carbs": 20,
   "sugar": 0,
   "Display Shelf": 1,
   "potassium": 120,
   "vitamins": 0,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.67
 },
 {
   "name": "Smacks",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 2,
   "Fat": 1,
   "Sodium": 70,
   "Dietary Fiber": 1,
   "Carbs": 9,
   "sugar": 15,
   "Display Shelf": 2,
   "potassium": 40,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.75
 },
 {
   "name": "Special_K",
   "manufacturer": "Kelloggs",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 6,
   "Fat": 0,
   "Sodium": 230,
   "Dietary Fiber": 1,
   "Carbs": 16,
   "sugar": 3,
   "Display Shelf": 1,
   "potassium": 55,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 1
 },
 {
   "name": "Strawberry_Fruit_Wheats",
   "manufacturer": "Nabisco",
   "Type": "C",
   "calories": 90,
   "Protein (g)": 2,
   "Fat": 0,
   "Sodium": 15,
   "Dietary Fiber": 3,
   "Carbs": 15,
   "sugar": 5,
   "Display Shelf": 2,
   "potassium": 90,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": -1
 },
 {
   "name": "Total_Corn_Flakes",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 2,
   "Fat": 1,
   "Sodium": 200,
   "Dietary Fiber": 0,
   "Carbs": 21,
   "sugar": 3,
   "Display Shelf": 3,
   "potassium": 35,
   "vitamins": 100,
   "Serving Size Weight": 1,
   "Cups per Serving": 1
 },
 {
   "name": "Total_Raisin_Bran",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 140,
   "Protein (g)": 3,
   "Fat": 1,
   "Sodium": 190,
   "Dietary Fiber": 4,
   "Carbs": 15,
   "sugar": 14,
   "Display Shelf": 3,
   "potassium": 230,
   "vitamins": 100,
   "Serving Size Weight": 1.5,
   "Cups per Serving": 1
 },
 {
   "name": "Total_Whole_Grain",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 100,
   "Protein (g)": 3,
   "Fat": 1,
   "Sodium": 200,
   "Dietary Fiber": 3,
   "Carbs": 16,
   "sugar": 3,
   "Display Shelf": 3,
   "potassium": 110,
   "vitamins": 100,
   "Serving Size Weight": 1,
   "Cups per Serving": 1
 },
 {
   "name": "Triples",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 2,
   "Fat": 1,
   "Sodium": 250,
   "Dietary Fiber": 0,
   "Carbs": 21,
   "sugar": 3,
   "Display Shelf": 3,
   "potassium": 60,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.75
 },
 {
   "name": "Trix",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 1,
   "Fat": 1,
   "Sodium": 140,
   "Dietary Fiber": 0,
   "Carbs": 13,
   "sugar": 12,
   "Display Shelf": 2,
   "potassium": 25,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 1
 },
 {
   "name": "Wheat_Chex",
   "manufacturer": "Ralston Purina",
   "Type": "C",
   "calories": 100,
   "Protein (g)": 3,
   "Fat": 1,
   "Sodium": 230,
   "Dietary Fiber": 3,
   "Carbs": 17,
   "sugar": 3,
   "Display Shelf": 1,
   "potassium": 115,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.67
 },
 {
   "name": "Wheaties",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 100,
   "Protein (g)": 3,
   "Fat": 1,
   "Sodium": 200,
   "Dietary Fiber": 3,
   "Carbs": 17,
   "sugar": 3,
   "Display Shelf": 1,
   "potassium": 110,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 1
 },
 {
   "name": "Wheaties_Honey_Gold",
   "manufacturer": "General Mills",
   "Type": "C",
   "calories": 110,
   "Protein (g)": 2,
   "Fat": 1,
   "Sodium": 200,
   "Dietary Fiber": 1,
   "Carbs": 16,
   "sugar": 8,
   "Display Shelf": 1,
   "potassium": 60,
   "vitamins": 25,
   "Serving Size Weight": 1,
   "Cups per Serving": 0.75
 }
]
